dictionnaire = {

"some dirty rag" : "sujet",
"some dog" : "sujet",
"someone insane" : "sujet",
"this place" : "sujet",
"you" : "sujet",
"your teacher" : "sujet",
"your mother" : "sujet",
"your sense of style" : "sujet",
"your sister" : "sujet",
"your sins" : "sujet",
"your son" : "sujet",
"your wife"  : "sujet",

"is" : "verbe",
"wanted to be" : "verbe",
"is rude" : "verbe",
"is silly" : "verbe",
"is vile" : "verbe",
"was in jail" : "verbe",
"have bad breath" : "verbe",
"have bum cancer"  : "verbe",
"have tiny feet" : "verbe",
"acts like" : "verbe",
"admires pictures of" : "verbe",
"can be found in Pokémon GO" : "verbe",
"can't dance" : "verbe",
"can't exercise because of" : "verbe",
"can't hold liquor" : "verbe",
"changes into" : "verbe",
"dances like" : "verbe",
"died because of" : "verbe",
"donated organ for" : "verbe",
"enjoyed Batman v Superman" : "verbe",
"farted on" : "verbe",
"likes to flash in the park" : "verbe",
"looks like" : "verbe",
"makes me sick" : "verbe",
"moves like a pregnant yak" : "verbe",
"needs a liver transplant" : "verbe",
"never watched Star Wars" : "verbe",
"pissed on" : "verbe",
"pre-ordered No Man's Sky" : "verbe",
"poses nude for" : "verbe",
"puts on granny's clothin" : "verbe",
"secretly adores" : "verbe",
"smells of" : "verbe",
"stalked" : "verbe",
"still use(s) Windows Vista" : "verbe",
"supports" : "verbe",
"swallowed a chewing gum" : "verbe",
"talks to strangers" : "verbe",
"tastes like" : "verbe",
"tells dirty jokes at funerals" : "verbe",
"vomits after drinking vodka" : "verbe",
"walks silly" : "verbe",
"worked with" : "verbe",

"and" : "liaison",
"on" : "liaison",
}
